### ISSUE TITLE
How to direct download the entire game?

### ISSUE THREAD

**Issue by BigBellyKing** [DevonTM/genshin-updater#1]

**Comment by DevonTM** [comment]
You can find the direct download link [here](https://hk4e-launcher-static.hoyoverse.com/hk4e_global/mdk/launcher/api/resource?channel_id=1&key=gcStgarh&launcher_id=10&sub_channel_id=0), use json formatter or something like that so you can easily find the correct link. I think the link is under data > game > latest > segments which is splitted into 6 part. Don't forget to download the voice packs too.

**Comment by BigBellyKing** [comment]
Thank you so much it works~
